### ISSUE TITLE
Not AOT compilation

### ISSUE THREAD

**Issue by newalopez** [kiwigrid/ngx-daterangepicker#14]
Without --aot, the project won't compile:

ngx-daterangepicker/src/ngx-daterangepicker/index.ts is not part of the compilation output.

**Comment by stefanmeschke** [comment]
Hey,

we tried it with the newest version and everything was fine.

**Tested with:**
- Angular CLI version 1.6.8
- Angular version 5.2.0
- ngx-daterangepicker version 0.5.1

Which versions do you have? Please give us more information about your environment.


Cheers
@marcelkilian and Stefan

**Comment by newalopez** [comment]
Sorry for so little information, and also, thanks for great component.

Angular CLI: 1.6.0
Node: 7.4.0
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router


package.json:
    "ngx-daterangepicker": "^0.7.0",


After some updates, now I have a new error:
Angular CLI: 1.7.3
Node: 7.4.0
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

ERROR in ./node_modules/ngx-daterangepicker/src/ngx-daterangepicker/index.ts
Module build failed: Error: node_modules/ngx-daterangepicker/src/ngx-daterangepicker/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by stefanmeschke** [comment]
Quick reply to help you immediately:
The package you`ve mentioned is not the package which is maintained with this GitHub repository.

Link to your package: https://www.npmjs.com/package/ngx-daterangepicker

Maybe you give our package a try. ;)

Cheers

**Comment by newalopez** [comment]
Oh sorry, good thing the properties are the same, I'll try yours, demo runs nice.

Regards.
