### ISSUE TITLE
I am using date range picker in popup, I need option to resize and hide right panel

### ISSUE THREAD

**Issue by dineshdedhia** [kiwigrid/ngx-daterangepicker#6]

**Comment by dineshdedhia** [comment]
Eg: Something like this width="150px"

**Comment by dineshdedhia** [comment]
Hello Kiwigrid,
Eg: Something like this width="150px"

![date-range](https://cloud.githubusercontent.com/assets/12005733/25229135/bf4f6d9c-25ec-11e7-9fb5-2b98f5bbff07.jpg)
,

**Comment by Norreman** [comment]
Hi dineshdedhia, you can access width an visibily of the elements by css rules in your project.

**Comment by dineshdedhia** [comment]
Hi @Norreman,
Thanks alot :) Cheers 
Its Done.
