### ISSUE TITLE
Difference between selecting presets vs. manual

### ISSUE THREAD

**Issue by Norreman** [kiwigrid/ngx-daterangepicker#7]
By selecting a preset, the time range is from "startofDay" of the beginning till "endOfDay" of ending. By selecting the same time range manual, the time range is from "startofDay" of the beginning till "startOfDay" of ending. This ist wrong. On manual selecting it must also be "endOfDay" of the beginning.

**Comment by matthiaskomarek** [comment]
fixed with #8
